### ISSUE TITLE
'Invalid hook call' when adding redux

### ISSUE THREAD

**Issue by vegar** [zenghongtu/create-electron-react#3]
First: Thanks for a nice starter :-)

I'm trying to add react-redux to the game, but as soon as I'm including the `<Provider />`, I'm rewarded with this error message: 

> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

I've tried to follow the troubleshoot guide from the link in the error message. The `window.React1 == window.React2`-test returns false, but I'm not able to find the reason for it.

Reproduction is relatively easy: 

1. `npx create-electron-react invalid-hook && cd invalid-hook`
2. `npm i -S redux react-redux`
3. Modify `app.jsx`

```
diff --git a/src/renderer/App.jsx b/src/renderer/App.jsx
index 03e7c1c..b05457f 100644
--- a/src/renderer/App.jsx
+++ b/src/renderer/App.jsx

@@ -3,6 +3,20 @@ 
 import { hot } from "react-hot-loader/root";
 import logo from "./assets/logo.svg";
 import "./App.css";
 import { remote } from "electron";
+import { createStore } from "redux";
+import { Provider } from "react-redux";
+
+function counter(state = 0, action) {
+  switch (action.type) {
+    case "INCREMENT":
+      return state + 1;
+    case "DECREMENT":
+      return state - 1;
+    default:
+      return state;
+  }
+}
+const store = createStore(counter);

 const App = () => {
   const electron = process.versions.electron;

@@ -16,6 +30,7 @@ 
 const App = () => {
   };

   return (
+    <Provider store={store}>
       <div className="App">
         <header className="App-header">
           <img src={logo} className="App-logo" alt="logo" />

@@ -58,6 +73,7 @@
 const App = () => {
           </div>
         </header>
       </div>
+    </Provider>
   );
 };
```

Do you have any idea what can cause this?

I've tried to reproduce it with `create-react-app`. There the same code seems to work ok.

**Comment by zenghongtu** [comment]
`.electron-react/webpack.renderer.config.js`

```js
...
const whiteListedModules = ['react', 'react-dom'];
```

`whiteListedModules` is for externals

**Comment by vegar** [comment]
Solved my issue!
Thanks!

Two tings, though: 
1. Why did dis solve anything? Will I need to add more libraries to this list later?
2. Upgrades... When going from 0.0.0.8 to 0.0.0.9, I ended up deleting everything and starting over. That's ok no when I just fiddle around to test and understand stuff, but later... Will you write some instructions or something for this?
